### ISSUE TITLE
Regarding Training Code

### ISSUE THREAD

**Issue by xbais** [valeoai/SALUDA#3]
:wave: Hi there @BjoernMichele ! 
Thanks for this amazing work :partying_face: :partying_face: . I wish to test the model on my custom target and source datasets. But it appears that the training scripts are not currently released in the repo.

Just wanted to ask by when will the code be published...
Thanks!

**Comment by BjoernMichele** [comment]
Dear @xbais, 

Thank  you very much for your interest in our work. The training code will be published in about 2 weeks, for the 3DV conference, where it will be presented. 

Best, 
Bjoern

**Comment by BjoernMichele** [comment]
Thank you again for your interest in our work and thank you for being patient to wait for the code. I just uploaded also the training code so that you can start with your custom dataset. 

With best regards, 
Bjoern

**Comment by xbais** [comment]
Great! Thanks a lot!
